### ISSUE TITLE
Improve replies handling

### ISSUE THREAD

**Issue by ryanrms** [tabasku/harbour-neliapila#4]
Would be great if you could just tap the icon showing a post has replies to see the replies.

Also, nested replies dont seem to work.  Holding and selecting "View Replies" works in the main thread, but if you select it on a reply when you are already viewing a reply, it loads a new screen with no posts.

**Comment by jacquesCedric** [comment]
Fixed with #15

**Comment by szopin** [comment]
Interestingly this fix also half-fixes replying to nested replies, but only on first level, also still throws a 'you are banned error', but reply goes through. Weirdly enough just went to reproduce and it seems like it works 50% of the time on the first nested replies, 0% on deeper, strange
